# Generated by Django 3.1.2 on 2020-12-20 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201219_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='replytimestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
