# Generated by Django 3.1.2 on 2020-12-25 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='hits',
            new_name='views',
        ),
    ]
